name: Build Windows App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          # 安装webview2
          Invoke-WebRequest https://go.microsoft.com/fwlink/p/?LinkId=2124703 -OutFile webview2.exe
          Start-Process -FilePath webview2.exe -Args "/silent /install" -Verb RunAs -Wait
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      
      - name: Generate pnpm-lock.yaml if missing
        run: |
          if (!(Test-Path "pnpm-lock.yaml")) {
            echo "未找到pnpm-lock.yaml文件，正在生成..."
            pnpm install --no-frozen-lockfile
          } else {
            echo "pnpm-lock.yaml文件已存在"
          }
        shell: pwsh
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Disable updater in tauri.conf.json
        run: |
          # 读取tauri.conf.json文件
          $tauriConfig = Get-Content -Path "./src-tauri/tauri.conf.json" -Raw | ConvertFrom-Json
          
          # 禁用updater功能
          if ($tauriConfig.plugins -and $tauriConfig.plugins.updater) {
            $tauriConfig.plugins.updater.active = $false
            echo "已禁用Tauri的updater功能"
          } else {
            echo "未找到updater配置，可能已禁用"
          }
          
          # 将修改后的配置写回文件
          $tauriConfig | ConvertTo-Json -Depth 10 | Set-Content -Path "./src-tauri/tauri.conf.json"
          
          # 显示修改后的配置
          echo "修改后的tauri.conf.json:"
          Get-Content -Path "./src-tauri/tauri.conf.json"
        shell: pwsh
      
      - name: Build Tauri app (continue on error)
        uses: tauri-apps/tauri-action@v0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "HuLa v__VERSION__"
          releaseBody: "请查看版本详情了解新功能。"
          releaseDraft: true
          prerelease: false
      
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HuLa-windows
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe 
