name: 生成Tauri签名密钥

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  generate-keys:
    runs-on: ubuntu-latest  # 使用Ubuntu环境，更可靠
    
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: 设置pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      
      - name: 安装依赖
        run: pnpm install
      
      - name: 安装Tauri CLI
        run: npm install -g @tauri-apps/cli
      
      - name: 生成Tauri签名密钥
        id: generate-keys
        run: |
          # 创建目录
          mkdir -p ./keys
          
          # 生成密钥，不使用密码保护（简化流程）
          tauri signer generate
          
          # 显示生成的密钥文件
          echo "生成的密钥文件:"
          ls -la ~/.tauri/
          
          # 读取私钥和公钥
          PRIVATE_KEY=$(cat ~/.tauri/identity.key)
          PUBLIC_KEY=$(cat ~/.tauri/identity.key.pub)
          
          # 将私钥和公钥保存到文件
          echo "$PRIVATE_KEY" > ./keys/tauri_private_key.txt
          echo "$PUBLIC_KEY" > ./keys/tauri_public_key.txt
          
          # 压缩密钥文件以便下载
          cd ./keys
          zip -r tauri-keys.zip *.txt
          cd ..
          
          # 以更友好的格式输出公钥（单行）
          echo "========== 公钥（用于配置文件） =========="
          echo "$PUBLIC_KEY" | tr -d '\n' | tr -d '\r'
          echo -e "\n"
          
          # 以更友好的格式输出私钥（用于GitHub Secrets）
          echo "========== 私钥（用于GitHub Secrets）=========="
          echo "$PRIVATE_KEY" | base64 | tr -d '\n'
          echo -e "\n"
          echo "注意：上面的私钥已经过base64编码，直接复制整行内容到GitHub Secrets中"
      
      - name: 上传密钥文件
        uses: actions/upload-artifact@v4
        with:
          name: tauri-keys
          path: ./keys/tauri-keys.zip
          retention-days: 1
      
      - name: 帮助信息
        run: |
          echo "====== 如何使用这些密钥 ======"
          echo "1. 从上面的输出中复制公钥（单行格式）"
          echo "2. 打开 src-tauri/tauri.conf.json 文件"
          echo "3. 找到 'plugins' > 'updater' > 'pubkey' 字段，替换为公钥内容"
          echo "4. 在GitHub仓库设置中添加Secret:"
          echo "   - 名称: TAURI_PRIVATE_KEY"
          echo "   - 值: 上面显示的base64编码私钥（整行复制）"
          echo "5. 如果您需要原始文件格式，可以下载上面的 tauri-keys 构建产物"
          echo "当您完成这些步骤后，请移除此工作流以避免安全风险！" 
