name: Release CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发工作流

# 确保默认情况下所有 job 都只有只读权限，只有需要写权限的 job（比如发布 release 的 job）才会单独提升权限，其他 job 依然保持最小权限，最大程度保护仓库安全
permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true  # 如果有新的发布任务，取消正在进行的任务

jobs:
  publish-tauri:
    permissions:
      contents: write # 授予写入仓库内容的权限
    strategy:
      fail-fast: false  # 某个平台构建失败不影响其他平台
      matrix:
        include:
          # 仅保留Windows构建
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # 添加环境变量配置
      - name: Set up environment variables
        run: echo "${{ secrets.ENV_LOCAL_CONTENT }}" > .env.local

      # 首先安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # 然后设置 Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Vite + Tauri
        run: pnpm build

      # 安装 Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ''

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Create release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用之前配置的私钥
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          # 使用之前配置的私钥密码
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ #这个动作会自动将\_\_VERSION\_\_替换为app version
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
